version: '3.9'

services:
  app:
    build: .
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: app

volumes:
  node_modules: