version: '3.9'

services:
  front:
    image: kurkkumopo-frontend
    ports:
      - 3000:3000
  
  back:
    image: kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    image: kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data

volumes:
  model:
  data:
  imgs: