version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_postgres
    expose:
      - 5432

  redis:
    image: redis
    container_name: cache
    expose:
      - 6739

  frontend:
    image: env-front
    ports:
      - 5000:5000

  backend:
    image: env-backend
    ports:
      - 8080:8080
    links:
      - redis
      - db
    environment:
          - REDIS_HOST=cache
          - POSTGRES_HOST=db_postgres
    depends_on:
      - db